#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MOTOR_STEP_PER_REVOLUTION 	200
#define MOTOR_SPEED			60
#define MOTOR_STEP_TO_SWITCH		260
#define MOTOR_DIR_DOWN				BACKWARD
#define MOTOR_DIR_UP				FORWARD

#define SERIAL_BAUDRATE				57600

#endif
