#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MOTORS_STEP_PER_REVOLUTION 	200
#define MOTORS_SPEED				60
#define MOTORS_STEP_TO_SWITCH		260
#define MOTOR1_DIR_DOWN				FORWARD
#define MOTOR1_DIR_UP				BACKWARD
#define MOTOR2_DIR_DOWN				FORWARD
#define MOTOR2_DIR_UP				BACKWARD

#define SERIAL_BAUDRATE				57600

#endif
