#!/bin/bash

echo -e '\e[32;1mBuilding asserv mega\e[0;0m'
scons -c > /dev/null 2>&1
scons --sconstruct SConstruct.mega2560 > /dev/null 2> log.tmp
rc=$?
if [[ $rc != 0 ]] ; then
	cat log.tmp
	echo -e '\e[31;1mAsserv mega failed\e[0;0m'
	exit 1
else
	echo -e '\e[32;1mAsserv mega OK\e[0;0m'
fi
if [[ $1 == -c ]] ; then
	scons -c > /dev/null &
fi

echo -e '\e[32;1mBuilding asserv nano\e[0;0m'
scons -c > /dev/null 2>&1
scons --sconstruct SConstruct.nano328 > /dev/null 2> log.tmp
rc=$?
if [[ $rc != 0 ]] ; then
	cat log.tmp
	echo -e '\e[31;1mAsserv nano failed\e[0;0m'
	exit 1
else
	echo -e '\e[32;1mAsserv nano OK\e[0;0m'
fi
if [[ $1 == -c ]] ; then
	scons -c > /dev/null &
fi

echo -e '\e[32;1mCleaning\e[0;0m'
scons -c > /dev/null 2>&1

rm log.tmp

exit 0
